version: '3.8'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - shared_volume:/var/lib/mysql

  redis:
    image: redis
    env_file:
      - .env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend

volumes:
  shared_volume:
    external: true
