FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

WORKDIR /usr/src/app

COPY Gemfile /usr/src/app/
COPY Gemfile.lock /usr/src/app/

COPY . /usr/src/app
RUN bundle install --without development test

CMD ["rails", "s", "-p", "3000", "-b", "0.0.0.0"]

EXPOSE 3000
